export const getCurrencyInfo = (shortCode: string) => {
  const currencyMap: { [key: string]: { name: string; symbol: string } } = {
    AFN: { name: "Afghan Afghani", symbol: "؋" },
    ALL: { name: "Albanian Lek", symbol: "L" },
    DZD: { name: "Algerian Dinar", symbol: "د.ج" },
    EUR: { name: "Euro", symbol: "€" },
    AOA: { name: "Angolan Kwanza", symbol: "Kz" },
    XCD: { name: "East Caribbean Dollar", symbol: "$" },
    ARS: { name: "Argentine Peso", symbol: "$" },
    AMD: { name: "Armenian Dram", symbol: "֏" },
    AUD: { name: "Australian Dollar", symbol: "A$" },
    AZN: { name: "Azerbaijani Manat", symbol: "₼" },
    BSD: { name: "Bahamian Dollar", symbol: "B$" },
    BHD: { name: "Bahraini Dinar", symbol: ".د.ب" },
    BDT: { name: "Bangladeshi Taka", symbol: "৳" },
    BBD: { name: "Barbadian Dollar", symbol: "Bds$" },
    BYN: { name: "Belarusian Ruble", symbol: "Br" },
    BZD: { name: "Belize Dollar", symbol: "BZ$" },
    BMD: { name: "Bermudian Dollar", symbol: "BD$" },
    BTN: { name: "Bhutanese Ngultrum", symbol: "Nu." },
    BOB: { name: "Bolivian Boliviano", symbol: "Bs." },
    BAM: { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
    BWP: { name: "Botswanan Pula", symbol: "P" },
    BRL: { name: "Brazilian Real", symbol: "R$" },
    BND: { name: "Brunei Dollar", symbol: "B$" },
    BGN: { name: "Bulgarian Lev", symbol: "лв" },
    BIF: { name: "Burundian Franc", symbol: "FBu" },
    XOF: { name: "West African CFA Franc", symbol: "CFA" },
    XAF: { name: "Central African CFA Franc", symbol: "FCFA" },
    XPF: { name: "CFP Franc", symbol: "₣" },
    KHR: { name: "Cambodian Riel", symbol: "៛" },
    CAD: { name: "Canadian Dollar", symbol: "C$" },
    CVE: { name: "Cape Verdean Escudo", symbol: "Esc" },
    KYD: { name: "Cayman Islands Dollar", symbol: "CI$" },
    CLP: { name: "Chilean Peso", symbol: "$" },
    CNY: { name: "Chinese Yuan", symbol: "¥" },
    COP: { name: "Colombian Peso", symbol: "$" },
    KMF: { name: "Comorian Franc", symbol: "CF" },
    CDF: { name: "Congolese Franc", symbol: "FC" },
    CRC: { name: "Costa Rican Colón", symbol: "₡" },
    HRK: { name: "Croatian Kuna", symbol: "kn" },
    CUP: { name: "Cuban Peso", symbol: "$" },
    CZK: { name: "Czech Koruna", symbol: "Kč" },
    DKK: { name: "Danish Krone", symbol: "kr" },
    DJF: { name: "Djiboutian Franc", symbol: "Fdj" },
    DOP: { name: "Dominican Peso", symbol: "RD$" },
    EGP: { name: "Egyptian Pound", symbol: "E£" },
    ERN: { name: "Eritrean Nakfa", symbol: "Nfk" },
    SZL: { name: "Swazi Lilangeni", symbol: "L" },
    ETB: { name: "Ethiopian Birr", symbol: "Br" },
    FJD: { name: "Fijian Dollar", symbol: "FJ$" },
    GMD: { name: "Gambian Dalasi", symbol: "D" },
    GEL: { name: "Georgian Lari", symbol: "₾" },
    GHS: { name: "Ghanaian Cedi", symbol: "GH₵" },
    GIP: { name: "Gibraltar Pound", symbol: "£" },
    GTQ: { name: "Guatemalan Quetzal", symbol: "Q" },
    GNF: { name: "Guinean Franc", symbol: "FG" },
    GYD: { name: "Guyanese Dollar", symbol: "GY$" },
    HTG: { name: "Haitian Gourde", symbol: "G" },
    HNL: { name: "Honduran Lempira", symbol: "L" },
    HKD: { name: "Hong Kong Dollar", symbol: "HK$" },
    HUF: { name: "Hungarian Forint", symbol: "Ft" },
    ISK: { name: "Icelandic Króna", symbol: "kr" },
    INR: { name: "Indian Rupee", symbol: "₹" },
    IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
    IRR: { name: "Iranian Rial", symbol: "﷼" },
    IQD: { name: "Iraqi Dinar", symbol: "ع.د" },
    ILS: { name: "Israeli New Shekel", symbol: "₪" },
    JMD: { name: "Jamaican Dollar", symbol: "J$" },
    JPY: { name: "Japanese Yen", symbol: "¥" },
    JOD: { name: "Jordanian Dinar", symbol: "د.ا" },
    KZT: { name: "Kazakhstani Tenge", symbol: "₸" },
    KES: { name: "Kenyan Shilling", symbol: "KSh" },
    KWD: { name: "Kuwaiti Dinar", symbol: "د.ك" },
    KGS: { name: "Kyrgyzstani Som", symbol: "с" },
    LAK: { name: "Laotian Kip", symbol: "₭" },
    LBP: { name: "Lebanese Pound", symbol: "ل.ل" },
    LSL: { name: "Lesotho Loti", symbol: "L" },
    LRD: { name: "Liberian Dollar", symbol: "L$" },
    LYD: { name: "Libyan Dinar", symbol: "ل.د" },
    MOP: { name: "Macanese Pataca", symbol: "MOP$" },
    MKD: { name: "Macedonian Denar", symbol: "ден" },
    MGA: { name: "Malagasy Ariary", symbol: "Ar" },
    MWK: { name: "Malawian Kwacha", symbol: "MK" },
    MYR: { name: "Malaysian Ringgit", symbol: "RM" },
    MVR: { name: "Maldivian Rufiyaa", symbol: "Rf" },
    MRU: { name: "Mauritanian Ouguiya", symbol: "UM" },
    MUR: { name: "Mauritian Rupee", symbol: "₨" },
    MXN: { name: "Mexican Peso", symbol: "MX$" },
    MDL: { name: "Moldovan Leu", symbol: "L" },
    MNT: { name: "Mongolian Tögrög", symbol: "₮" },
    MAD: { name: "Moroccan Dirham", symbol: "د.م." },
    MZN: { name: "Mozambican Metical", symbol: "MT" },
    MMK: { name: "Myanmar Kyat", symbol: "K" },
    NAD: { name: "Namibian Dollar", symbol: "N$" },
    NPR: { name: "Nepalese Rupee", symbol: "₨" },
    ANG: { name: "Netherlands Antillean Guilder", symbol: "ƒ" },
    NZD: { name: "New Zealand Dollar", symbol: "NZ$" },
    NIO: { name: "Nicaraguan Córdoba", symbol: "C$" },
    NGN: { name: "Nigerian Naira", symbol: "₦" },
    KPW: { name: "North Korean Won", symbol: "₩" },
    NOK: { name: "Norwegian Krone", symbol: "kr" },
    OMR: { name: "Omani Rial", symbol: "ر.ع." },
    PKR: { name: "Pakistani Rupee", symbol: "₨" },
    PAB: { name: "Panamanian Balboa", symbol: "B/." },
    PGK: { name: "Papua New Guinean Kina", symbol: "K" },
    PYG: { name: "Paraguayan Guaraní", symbol: "₲" },
    PEN: { name: "Peruvian Sol", symbol: "S/." },
    PHP: { name: "Philippine Peso", symbol: "₱" },
    PLN: { name: "Polish Złoty", symbol: "zł" },
    QAR: { name: "Qatari Riyal", symbol: "ر.ق" },
    RON: { name: "Romanian Leu", symbol: "lei" },
    RUB: { name: "Russian Ruble", symbol: "₽" },
    RWF: { name: "Rwandan Franc", symbol: "FRw" },
    SHP: { name: "Saint Helena Pound", symbol: "£" },
    WST: { name: "Samoan Tala", symbol: "T" },
    STN: { name: "São Tomé and Príncipe Dobra", symbol: "Db" },
    SAR: { name: "Saudi Riyal", symbol: "ر.س" },
    RSD: { name: "Serbian Dinar", symbol: "дин" },
    SCR: { name: "Seychellois Rupee", symbol: "₨" },
    SLL: { name: "Sierra Leonean Leone", symbol: "Le" },
    SGD: { name: "Singapore Dollar", symbol: "S$" },
    SBD: { name: "Solomon Islands Dollar", symbol: "SI$" },
    SOS: { name: "Somali Shilling", symbol: "Sh" },
    ZAR: { name: "South African Rand", symbol: "R" },
    KRW: { name: "South Korean Won", symbol: "₩" },
    SSP: { name: "South Sudanese Pound", symbol: "£" },
    LKR: { name: "Sri Lankan Rupee", symbol: "Rs" },
    SDG: { name: "Sudanese Pound", symbol: "ج.س." },
    SRD: { name: "Surinamese Dollar", symbol: "$" },
    SEK: { name: "Swedish Krona", symbol: "kr" },
    CHF: { name: "Swiss Franc", symbol: "CHF" },
    SYP: { name: "Syrian Pound", symbol: "£" },
    TWD: { name: "New Taiwan Dollar", symbol: "NT$" },
    TJS: { name: "Tajikistani Somoni", symbol: "ЅМ" },
    TZS: { name: "Tanzanian Shilling", symbol: "TSh" },
    THB: { name: "Thai Baht", symbol: "฿" },
    TOP: { name: "Tongan Paʻanga", symbol: "T$" },
    TTD: { name: "Trinidad and Tobago Dollar", symbol: "TT$" },
    TND: { name: "Tunisian Dinar", symbol: "د.ت" },
    TRY: { name: "Turkish Lira", symbol: "₺" },
    TMT: { name: "Turkmenistani Manat", symbol: "T" },
    UGX: { name: "Ugandan Shilling", symbol: "USh" },
    UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
    AED: { name: "United Arab Emirates Dirham", symbol: "د.إ" },
    GBP: { name: "British Pound", symbol: "£" },
    USD: { name: "United States Dollar", symbol: "$" },
    UYU: { name: "Uruguayan Peso", symbol: "$U" },
    UZS: { name: "Uzbekistani Som", symbol: "so'm" },
    VUV: { name: "Vanuatu Vatu", symbol: "VT" },
    VES: { name: "Venezuelan Bolívar", symbol: "Bs." },
    VND: { name: "Vietnamese Đồng", symbol: "₫" },
    YER: { name: "Yemeni Rial", symbol: "﷼" },
    ZMW: { name: "Zambian Kwacha", symbol: "ZK" },
    ZWL: { name: "Zimbabwean Dollar", symbol: "Z$" },
  };
  
  if (!currencyMap[shortCode]) {
    console.warn(`Currency not found for code: ${shortCode}`);
    return { name: `Currency (${shortCode})`, symbol: shortCode };
  }
  
  return currencyMap[shortCode];
}; 